/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE2_H_RPCGEN
#define _INTERFACE2_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define TAM_MAX_NOM_ARCHIVO 128
#define TAM_MAX_BLOQUE_ARCHIVO 1024

struct bloque_1 {
	char *nombreArchivo;
	struct {
		u_int datos_len;
		char *datos_val;
	} datos;
	int size;
	int dest_offset;
};
typedef struct bloque_1 bloque_1;


#define interface2 0x22000002
#define interface2_version_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define crearCopiaCancion 1
extern  int * crearcopiacancion_1(char **, CLIENT *);
extern  int * crearcopiacancion_1_svc(char **, struct svc_req *);
#define enviarCopiaCancion 2
extern  int * enviarcopiacancion_1(bloque_1 *, CLIENT *);
extern  int * enviarcopiacancion_1_svc(bloque_1 *, struct svc_req *);
extern int interface2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define crearCopiaCancion 1
extern  int * crearcopiacancion_1();
extern  int * crearcopiacancion_1_svc();
#define enviarCopiaCancion 2
extern  int * enviarcopiacancion_1();
extern  int * enviarcopiacancion_1_svc();
extern int interface2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_bloque_1 (XDR *, bloque_1*);
extern  bool_t xdr_bloque_1 (XDR *, bloque_1*);

#else /* K&R C */
extern bool_t xdr_bloque_1 ();
extern bool_t xdr_bloque_1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE2_H_RPCGEN */
