/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTERFACE3_H_RPCGEN
#define _INTERFACE3_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNOM 30

struct nodo_cancion_1 {
	int id;
	char titulo[MAXNOM];
	char tipo[MAXNOM];
	double peso;
};
typedef struct nodo_cancion_1 nodo_cancion_1;


#define interface3 0x22000003
#define interface3_version_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define notificarRegistroCancion 1
extern  int * notificarregistrocancion_1(nodo_cancion_1 *, CLIENT *);
extern  int * notificarregistrocancion_1_svc(nodo_cancion_1 *, struct svc_req *);
extern int interface3_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define notificarRegistroCancion 1
extern  int * notificarregistrocancion_1();
extern  int * notificarregistrocancion_1_svc();
extern int interface3_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nodo_cancion_1 (XDR *, nodo_cancion_1*);
extern  bool_t xdr_nodo_cancion_1 (XDR *, nodo_cancion_1*);

#else /* K&R C */
extern bool_t xdr_nodo_cancion_1 ();
extern bool_t xdr_nodo_cancion_1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTERFACE3_H_RPCGEN */
