/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "interface3.h"

bool_t
xdr_nodo_cancion_1 (XDR *xdrs, nodo_cancion_1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, MAXNOM,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->peso))
		 return FALSE;
	return TRUE;
}
